### ISSUE TITLE
Blinding data from some hists in plotting

### ISSUE THREAD

**Issue by andreypz** [PocketCoffea/PocketCoffea#175]
It may be useful (or necessary) to blind the data in some histograms. It would be nice if such feauture existed in pocket coffea.
I think this could be implemented with the following syntax in the plotting config:
```yaml
  blind_hists:
      categories:
               - SigRegion1
               - SigRegion2
       histograms:
               - mjj: [100, 150]
               - BDT: [0.5, 1]
               
```
